"""Run final-output-level Q1 convergence checks before workbook generation.

The script compares the actual 1..1800 s x 0.0..2.0 cm deliverable grid and
the 7 x 5 paper-table subset. It writes JSON/Markdown evidence only; the
candidate workbook is generated by a separate artifact-tool builder after a
PASS.
"""

from __future__ import annotations

import json
import platform
import subprocess
import sys
import time
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path
from typing import Any, Dict, Iterable, List, Sequence, Tuple

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.validate_inputs import sha256
from src.common.paths import assert_not_official_output
from src.q1.config import DEFAULT_PARAMETERS, Q1RunConfig
from src.q1.inputs import BoundaryProvider
from src.q1.solver import Q1Result, run_m1


OUTPUT_TIMES_S = tuple(range(1, 1801))
OUTPUT_POSITIONS_M = tuple(index * 0.001 for index in range(21))
PAPER_TIMES_S = (100, 300, 600, 900, 1200, 1500, 1800)
PAPER_POSITIONS_M = (0.0, 0.005, 0.01, 0.015, 0.02)
ROUNDING_QUANTUM = Decimal("0.0001")


def _config(n_intervals: int, time_step_s: float) -> Q1RunConfig:
    return Q1RunConfig(
        end_time_s=1800.0,
        time_step_s=time_step_s,
        n_intervals=n_intervals,
        interpolation="linear",
        surface_boundary="robin",
    )


def _run(config: Q1RunConfig) -> Q1Result:
    boundary = BoundaryProvider.from_attachment1(ROOT / config.input_path)
    return run_m1(config, boundary, DEFAULT_PARAMETERS)


def _space_indices(result: Q1Result, positions_m: Sequence[float]) -> Tuple[int, ...]:
    indices = tuple(round(position / result.grid.dr_m) for position in positions_m)
    if any(index < 0 or index > result.grid.n_intervals for index in indices):
        raise ValueError("requested output position is outside the solver grid")
    if any(abs(index * result.grid.dr_m - position) > 1.0e-12 for index, position in zip(indices, positions_m)):
        raise ValueError("solver grid does not strictly align with requested output positions")
    return indices


def _time_indices(result: Q1Result, times_s: Sequence[int]) -> Tuple[int, ...]:
    indices = tuple(round(time_s / result.config.time_step_s) for time_s in times_s)
    if any(index >= len(result.times_s) or abs(result.times_s[index] - time_s) > 1.0e-9 for index, time_s in zip(indices, times_s)):
        raise ValueError("solver history does not contain an exact requested output time")
    return indices


def _output_rows(result: Q1Result, times_s: Sequence[int], positions_m: Sequence[float]) -> Dict[str, List[List[float]]]:
    time_indices = _time_indices(result, times_s)
    space_indices = _space_indices(result, positions_m)
    return {
        "temperature_c": [[result.temperatures_k[t][r] - 273.15 for r in space_indices] for t in time_indices],
        "moisture_kg_kg": [[result.moistures_kg_kg[t][r] for r in space_indices] for t in time_indices],
    }


def _flatten(rows: Iterable[Iterable[float]]) -> List[float]:
    return [value for row in rows for value in row]


def _raw_stats(first: Sequence[float], second: Sequence[float]) -> Dict[str, float]:
    differences = [abs(left - right) for left, right in zip(first, second)]
    return {"max_abs": max(differences), "mean_abs": sum(differences) / len(differences)}


def _round4(value: float) -> Decimal:
    return Decimal(str(value)).quantize(ROUNDING_QUANTUM, rounding=ROUND_HALF_UP)


def _rounded_stats(
    first: Dict[str, List[List[float]]],
    second: Dict[str, List[List[float]]],
    times_s: Sequence[int],
    positions_m: Sequence[float],
) -> Dict[str, Any]:
    total_cells = len(times_s) * len(positions_m)
    different_locations: List[Dict[str, Any]] = []
    by_field: Dict[str, Dict[str, Any]] = {}
    for field in ("temperature_c", "moisture_kg_kg"):
        different_count = 0
        first_values = _flatten(first[field])
        second_values = _flatten(second[field])
        for flat_index, (left, right) in enumerate(zip(first_values, second_values)):
            if _round4(left) != _round4(right):
                different_count += 1
                if len(different_locations) < 20:
                    row_index, col_index = divmod(flat_index, len(positions_m))
                    different_locations.append(
                        {
                            "field": field,
                            "time_s": times_s[row_index],
                            "distance_cm": positions_m[col_index] * 100.0,
                            "first_rounded": str(_round4(left)),
                            "second_rounded": str(_round4(right)),
                            "raw_abs_difference": abs(left - right),
                        }
                    )
        by_field[field] = {
            "different_count": different_count,
            "total_cells": total_cells,
            "different_fraction": different_count / total_cells,
        }
    return {
        "by_field": by_field,
        "different_count_total": sum(item["different_count"] for item in by_field.values()),
        "total_cells_all_fields": total_cells * len(by_field),
        "different_locations_first_20": different_locations,
    }


def _comparison(first: Q1Result, second: Q1Result, first_label: str, second_label: str) -> Dict[str, Any]:
    full_first = _output_rows(first, OUTPUT_TIMES_S, OUTPUT_POSITIONS_M)
    full_second = _output_rows(second, OUTPUT_TIMES_S, OUTPUT_POSITIONS_M)
    paper_first = _output_rows(first, PAPER_TIMES_S, PAPER_POSITIONS_M)
    paper_second = _output_rows(second, PAPER_TIMES_S, PAPER_POSITIONS_M)
    full_raw = {
        field: _raw_stats(_flatten(full_first[field]), _flatten(full_second[field]))
        for field in ("temperature_c", "moisture_kg_kg")
    }
    paper_raw = {
        field: _raw_stats(_flatten(paper_first[field]), _flatten(paper_second[field]))
        for field in ("temperature_c", "moisture_kg_kg")
    }
    center_raw = {
        field: _raw_stats(
            [row[0] for row in full_first[field]],
            [row[0] for row in full_second[field]],
        )
        for field in ("temperature_c", "moisture_kg_kg")
    }
    surface_raw = {
        field: _raw_stats(
            [row[-1] for row in full_first[field]],
            [row[-1] for row in full_second[field]],
        )
        for field in ("temperature_c", "moisture_kg_kg")
    }
    full_rounded = _rounded_stats(full_first, full_second, OUTPUT_TIMES_S, OUTPUT_POSITIONS_M)
    paper_rounded = _rounded_stats(paper_first, paper_second, PAPER_TIMES_S, PAPER_POSITIONS_M)
    return {
        "first": first_label,
        "second": second_label,
        "level_a_raw_difference": {
            "full_output_grid": full_raw,
            "paper_table_points": paper_raw,
            "center_over_full_time": center_raw,
            "surface_over_full_time": surface_raw,
        },
        "level_b_reported_value_stability": {
            "full_output_grid": full_rounded,
            "paper_table_points": paper_rounded,
            "pass": full_rounded["different_count_total"] == 0 and paper_rounded["different_count_total"] == 0,
        },
    }


def _comparison_pass(comparison: Dict[str, Any]) -> bool:
    return bool(comparison["level_b_reported_value_stability"]["pass"])


def _serializable_config(config: Q1RunConfig) -> Dict[str, Any]:
    return {
        field: (str(value) if isinstance(value, Path) else value)
        for field, value in vars(config).items()
    }


def _write_evidence(payload: Dict[str, Any]) -> Path:
    output_dir = assert_not_official_output(ROOT / "experiments" / "EXP-Q1-FINAL-CONV")
    output_dir.mkdir(parents=True, exist_ok=True)
    artifacts = [
        "experiments/EXP-Q1-FINAL-CONV/config.json",
        "experiments/EXP-Q1-FINAL-CONV/metrics.json",
        "experiments/EXP-Q1-FINAL-CONV/notes.md",
    ]
    payload["artifact_paths"] = artifacts
    (output_dir / "config.json").write_text(
        json.dumps(
            {
                "experiment_id": payload["experiment_id"],
                "code_commit": payload["code_commit"],
                "input_hashes": payload["input_hashes"],
                "model_parameters": payload["model_parameters"],
                "candidate_configurations": payload["candidate_configurations"],
                "selection": payload["selection"],
                "artifact_paths": artifacts,
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    (output_dir / "metrics.json").write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (output_dir / "notes.md").write_text(
        "# EXP-Q1-FINAL-CONV\n\n"
        "Final-output-level convergence compares raw values and values rounded to four decimals. "
        "No workbook was generated by this experiment.\n\n"
        f"Status: `{payload['status']}`\n\nRuntime: `{payload['runtime_seconds']:.6f} s`\n",
        encoding="utf-8",
    )
    return output_dir


def main() -> int:
    started = time.perf_counter()
    spatial_runs: Dict[str, Q1Result] = {
        "N80_dt0.25": _run(_config(80, 0.25)),
        "N160_dt0.25": _run(_config(160, 0.25)),
    }
    spatial_comparisons: Dict[str, Any] = {
        "N80_vs_N160": _comparison(spatial_runs["N80_dt0.25"], spatial_runs["N160_dt0.25"], "N80_dt0.25", "N160_dt0.25")
    }
    selected_n = 80
    spatial_reference = "N160_dt0.25"
    if not _comparison_pass(spatial_comparisons["N80_vs_N160"]):
        spatial_runs["N320_dt0.25"] = _run(_config(320, 0.25))
        spatial_comparisons["N160_vs_N320"] = _comparison(
            spatial_runs["N160_dt0.25"], spatial_runs["N320_dt0.25"], "N160_dt0.25", "N320_dt0.25"
        )
        selected_n = 160 if _comparison_pass(spatial_comparisons["N160_vs_N320"]) else 320
        spatial_reference = "N320_dt0.25" if selected_n == 160 else "N160_dt0.25"

    time_runs = {
        "dt1.0": _run(_config(selected_n, 1.0)),
        "dt0.5": _run(_config(selected_n, 0.5)),
        "dt0.25": _run(_config(selected_n, 0.25)),
    }
    time_comparisons = {
        "dt1.0_vs_dt0.5": _comparison(time_runs["dt1.0"], time_runs["dt0.5"], "dt1.0", "dt0.5"),
        "dt0.5_vs_dt0.25": _comparison(time_runs["dt0.5"], time_runs["dt0.25"], "dt0.5", "dt0.25"),
        "dt1.0_vs_dt0.25": _comparison(time_runs["dt1.0"], time_runs["dt0.25"], "dt1.0", "dt0.25"),
    }
    if _comparison_pass(time_comparisons["dt1.0_vs_dt0.25"]):
        selected_dt = 1.0
    elif _comparison_pass(time_comparisons["dt0.5_vs_dt0.25"]):
        selected_dt = 0.5
    else:
        selected_dt = 0.25

    selected_key = f"dt{selected_dt}"
    selected_time_pass = _comparison_pass(time_comparisons["dt1.0_vs_dt0.25"] if selected_dt == 1.0 else time_comparisons["dt0.5_vs_dt0.25"] if selected_dt == 0.5 else time_comparisons["dt1.0_vs_dt0.25"])
    spatial_pass = _comparison_pass(spatial_comparisons["N80_vs_N160"] if selected_n == 80 else spatial_comparisons.get("N160_vs_N320", spatial_comparisons["N80_vs_N160"]))
    status = "PASS" if spatial_pass and selected_time_pass else "BLOCKED"
    input_path = ROOT / "A题/附件/附件1.xlsx"
    commit = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()
    payload: Dict[str, Any] = {
        "experiment_id": "EXP-Q1-FINAL-CONV",
        "status": status,
        "command": ".\\.venv\\Scripts\\python.exe scripts\\run_q1_final_accuracy.py",
        "code_commit": commit,
        "input_hashes": {"A题/附件/附件1.xlsx": sha256(input_path)},
        "runtime_seconds": time.perf_counter() - started,
        "python": platform.python_version(),
        "model_parameters": {field: value for field, value in vars(DEFAULT_PARAMETERS).items()},
        "candidate_configurations": {
            key: _serializable_config(value.config)
            for key, value in {**spatial_runs, **time_runs}.items()
        },
        "selection": {
            "selected_n_intervals": selected_n,
            "selected_dr_m": DEFAULT_PARAMETERS.radius_m / selected_n,
            "selected_time_step_s": selected_dt,
            "spatial_reference": spatial_reference,
            "spatial_level_b_pass": spatial_pass,
            "time_level_b_pass": selected_time_pass,
            "selected_config_key": f"N{selected_n}_dt{selected_dt}",
        },
        "spatial_comparisons": spatial_comparisons,
        "time_comparisons": time_comparisons,
        "notes": "The lowest-cost configuration is selected only when complete output and paper-table values are stable after four-decimal rounding.",
    }
    _write_evidence(payload)
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    print(f"Evidence written to experiments/EXP-Q1-FINAL-CONV")
    return 0 if status == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
